export function createDom() {
  return {
    statusPill: document.getElementById("statusPill"),
    errors: document.getElementById("errors"),
    focusTitle: document.getElementById("focus-title"),
    focusRange: document.getElementById("focusRange"),
    focus: {
      sleepNow: document.getElementById("sleepNow"),
      sleepMeta: document.getElementById("sleepMeta"),
      sleepDay: document.getElementById("sleepDay"),
      sleepRange: document.getElementById("sleepRange"),
      stressCircle: document.getElementById("stressCircle"),
      stressNow: document.getElementById("stressNow"),
      stressMeta: document.getElementById("stressMeta"),
      stressNote: document.getElementById("stressNote"),
      exerciseNow: document.getElementById("exerciseNow"),
      exerciseMeta: document.getElementById("exerciseMeta"),
      exerciseDay: document.getElementById("exerciseDay"),
      exerciseNote: document.getElementById("exerciseNote"),
      bpNow: document.getElementById("bpNow"),
      bpMeta: document.getElementById("bpMeta"),
      bpNote: document.getElementById("bpNote"),
      weightNow: document.getElementById("weightNow"),
      weightMeta: document.getElementById("weightMeta"),
      weightNote: document.getElementById("weightNote"),
      nutritionNow: document.getElementById("nutritionNow"),
      nutritionMeta: document.getElementById("nutritionMeta"),
      nutritionDay: document.getElementById("nutritionDay"),
      nutritionRange: document.getElementById("nutritionRange"),
      nutritionMacros: document.getElementById("nutritionMacros"),
      nutritionCarbs: document.getElementById("nutritionCarbs"),
      nutritionProtein: document.getElementById("nutritionProtein"),
      nutritionFat: document.getElementById("nutritionFat"),
    },
    focusCharts: {
      sleep: document.getElementById("focusSleepChart"),
      stress: document.getElementById("focusStressChart"),
      exercise: document.getElementById("focusExerciseChart"),
      nutritionCalories: document.getElementById("focusNutritionCaloriesChart"),
      bp: document.getElementById("focusBpChart"),
      weight: document.getElementById("focusWeightChart"),
    },
    insights: {
      overallTitle: document.getElementById("insightOverallTitle"),
      overallBody: document.getElementById("insightOverallBody"),
      sleepTitle: document.getElementById("insightSleepTitle"),
      sleepBody: document.getElementById("insightSleepBody"),
      stressTitle: document.getElementById("insightStressTitle"),
      stressBody: document.getElementById("insightStressBody"),
      exerciseTitle: document.getElementById("insightExerciseTitle"),
      exerciseBody: document.getElementById("insightExerciseBody"),
      nutritionTitle: document.getElementById("insightNutritionTitle"),
      nutritionBody: document.getElementById("insightNutritionBody"),
      bpTitle: document.getElementById("insightBpTitle"),
      bpBody: document.getElementById("insightBpBody"),
      weightTitle: document.getElementById("insightWeightTitle"),
      weightBody: document.getElementById("insightWeightBody"),
    },
    tooltip: document.getElementById("tooltip"),
    rangeButtons: [...document.querySelectorAll("button[data-range-panel][data-range-days]")],
  };
}

